### PR TITLE
add updated Cody Enterprise architecture diagrams

### PR DESCRIPTION
**Pull request by sqs**

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
Markdown changes seem fine - for the contents of the Graphs I just trust you

One question: Is it true that Cody clients are fully SOC2 compliant today? 
Wondering, because in the last diagram for data flow, the SOC2 label is missing on the client, but present on the single-tenant SaaS.

**Comment by sqs** [comment]
> Markdown changes seem fine - for the contents of the Graphs I just trust you
> 
> One question: Is it true that Cody clients are fully SOC2 compliant today? Wondering, because in the last diagram for data flow, the SOC2 label is missing on the client, but present on the single-tenant SaaS.

Good pt. I will get a review from @sourcegraph/security-code-review.

**Review by MaedahBatool — APPROVED** [review]
These diagrams are 👌

**Comment by doragrgic** [comment]
LGTM - Cody VSCode agent is included in the SOC 2 Type 2 report scope. Bck when we did our last SOC2 audit JetBrains was not around so its not in audited scope yet but it will be included in the upcoming audit in June. 

I think for simplicity we can leave the SOC 2 badge on the whole extensions box in the architecture diagram.

**Review by doragrgic — APPROVED** [review]

**Comment by sqs** [comment]
Thank you, @doragrgic!

**Pull request merged**
