### PR TITLE
search: update Stream API doc page

### PR DESCRIPTION
**Pull request by stefanhengl**
This documents all supported query parameters and also updates the curl example.
I also removed the "The Stream API is still evolving" banner.

### CODE REVIEW

**Comment by jtibshirani** [comment]
This makes sense to me, but I'm wondering if there are certain parameters or design choices that we're not yet comfortable with? I'd be curious to hear from @keegancsmith and @camdencheek !

**Review by camdencheek — APPROVED** [review]
This is great -- thank you!

Unrelated to documenting it, but should we make chunk matches default true? I don't think we need to remove line matches (it's nearly zero maintenance burden), but given that we are only developing against chunk matches and some options (context lines) only work with chunk matches, I think it might make sense to encourage that as the default way to use the API.

**Review by jtibshirani — APPROVED** [review]
Ah, I thought that by removing the banner we were also declaring it "GA" and guaranteeing we won't make backwards incompatible changes. So that's why I was seeking broader input. Now I see this is likely not your intention?

For the docs updates themselves, +1 they look great!

**Comment by stefanhengl** [comment]
> Ah, I thought that by removing the banner we were also declaring it "GA" and guaranteeing we won't make backwards incompatible changes. 

That was my intention :-). But ... defaulting to chunk matches makes sense to me, too. We could change the default with the next release and announce it in the changelog.

**Pull request merged**
