### PR TITLE
Remove old entries of changelog

### PR DESCRIPTION
**Pull request by enriquegh**
We already only [support](https://sourcegraph.com/docs/sla#minimum-supported-version-for-self-hosted-instances) N-1 versions of Sourcegraph so having the entirety of our changelog in the docs seems like too much.
Additionally, our Algolia searchbar cannot index this entry because of its length.

### CODE REVIEW

**Comment by MaedahBatool** [comment]
@jhchabran with new incoming changes for our Changelog docs what's your suggestion for this PR? Should we merge it or keep it on hold for a while?

**Comment by jhchabran** [comment]
How many versions we keep in the changelog file is orthogonal to the proposed process for handling the changelog. 

Given this break the search feature, and searching in the changelog is the most basic feature ever, I think this problem should get fixed regardless. The proposed changes here makes sense to me.

**Comment by enriquegh** [comment]
@jhchabran 

> Also, it's quite strange that Algolia would choke on that file, do we know exactly where's the bottleneck?
When Algolia crawls a site it divides the contents into "records" and there is a limit of 750 records per page ([link](https://docsearch.algolia.com/docs/record-extractor/#reduce-the-number-of-records)).

There is a workaround by limiting the content that is indexed but in this case its just plain too much. There is a second workaround which is to run our own crawler which is something we can consider in the future.

**Comment by jhchabran** [comment]
@MaedahBatool I think we should merge this.

**Comment by enriquegh** [comment]
Resolved conflicts. With @MaedahBatool being out, if I can get an approval from you @jhchabran I can merge this.

**Review by jhchabran — APPROVED** [review]

**Pull request merged**
