### PR TITLE
docs: remove mentions of package code hosts

### PR DESCRIPTION
**Pull request by ggilmore**
We have no plans to work on this, so we are removing mentions of these package code hosts.

Fixes https://linear.app/sourcegraph/issue/SRC-721/remove-package-host-mentions-from-documentation

## Pull Request approval

Although pull request approval is not enforced for this repository in order to reduce friction, merging without a review will generate a ticket for the docs team to review your changes. So if possible, have your pull request approved before merging.

### CODE REVIEW

**Comment by ggilmore** [comment]
* **#724** <a href="https://app.graphite.dev/github/pr/sourcegraph/docs/724?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ggilmore and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by eseliger — APPROVED** [review]
seems ok to me, tagging @mmanela for additional input

**Comment by mmanela** [comment]
@eseliger  I agree to remove, we can always add back when we want to support

**Comment by ggilmore** [comment]
### Merge activity

* **Oct 21, 4:15 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/sourcegraph/docs/724).

**Pull request merged**
