### PR TITLE
Add docs for fetching SBOMs

### PR DESCRIPTION
**Pull request by willdollman**
Add public-facing docs for fetching SBOMs using `src`.

## Pull Request approval

Although pull request approval is not enforced for this repository in order to reduce friction, merging without a review will generate a ticket for the docs team to review your changes. So if possible, have your pull request approved before merging.

## TODO

- [x] Add screenshot of version
- [x] Make it clear that you don't need to install before fetching SBOMs
- [x] Add successful output from command
- [x] Update version in examples after release

### CODE REVIEW

**Comment by willdollman** [comment]
@MaedahBatool the Vercel preview for this PR (and others) seems to be broken. Is this something we're aware of?

**Review by evict — APPROVED** [review]
Looks good!

**Review by MaedahBatool — APPROVED** [review]
LGTM

**Comment by MaedahBatool** [comment]
> @MaedahBatool the Vercel preview for this PR (and others) seems to be broken. Is this something we're aware of?
> 
> @willdollman can you please add `/docs` at the end of the preview URL it will work then. Also, are these docs SG version contingent?

hey @willdollman is the Vercel issue solved or still not working?

**Comment by willdollman** [comment]
@MaedahBatool Yes, these changes only apply to 5.9 onwards so I was waiting until that release before merging - it was released yesterday so I can now merge. Is there anything special I need to do? The notion page is WIP https://www.notion.so/sourcegraph/Docs-Versioning-88d31f1e103343d2bdbc30a11595b384

Yes, the link works if you add /docs 👍  Can we fix the preview link?

Github doesn't send notifications if you edit someone's comment, so I only just saw your original message.

**Pull request merged**
