### PR TITLE
Update install-vscode.mdx

### PR DESCRIPTION
**Pull request by PriNova**
This update reflects the configuration parameters for the dev models according to the interface https://sourcegraph.com/github.com/sourcegraph/cody@c6f6909f3e9683570a695ef6e096eccaa20f6aaf/-/blob/vscode/src/models/sync.ts?L102-110

If configured with `token` as input token, it will not work properly and set 7000 tokens as default.

## Pull Request approval

Although pull request approval is not enforced for this repository in order to reduce friction, merging without a review will generate a ticket for the docs team to review your changes. So if possible, have your pull request approved before merging.

### CODE REVIEW

**Comment by aramaraju** [comment]
@abeatrix can you bless this docs change? I'm not close to this code, unfortunately.

**Comment by aramaraju** [comment]
> @aramaraju, would you like to take a quick review? :)

Haven't worked closely with this part of the code, so I'm deferring to Beatrix here

**Review by abeatrix — APPROVED** [review]

**Comment by PriNova** [comment]
Needs a review for merging @MaedahBatool

**Comment by PriNova** [comment]
This PR can be closed since the variable option parameters of the llm-provider have been changed to map the providers endpoint API.
Since this doc file needs a larger rewrite, I will open an new PR or someone else is ready for that.
Let me know.

Thank you

**Pull request closed without merging**
