### PR TITLE
Added content tabs component for sub-sections

### PR DESCRIPTION
**Pull request by zahidalidev**
This PR introduces the ContentTabs component for creating tabbed content in MDX files. The component handles tab switching and URL updates seamlessly without nesting issues.

# Usage Instructions

### Example Directory Structure
```
.
├── docs
│   └── cody
│       └── clients
│           ├── index.mdx
│           ├── install-vscode.mdx
│           ├── install-jetbrains.mdx
│           ├── install-neovim.mdx
│           ├── cody-with-sourcegraph.mdx
│           └── enable-cody-enterprise.mdx
```
### Main Tab Set (index.mdx)
- For the main tab set, typically in your index file (e.g., code/clients/index.mdx), use the ContentTabs component with the name prop set to 'main'.
- **Example: docs/cody/clients/index.mdx**
``` mdx
<ContentTabs name='main'>
  <ContentTab title="VS Code" href="/cody/clients/install-vscode" />
  <ContentTab title="JetBrains (beta)" href="/cody/clients/install-jetbrains" />
  <ContentTab title="Neovim (experimental)" href="/cody/clients/install-neovim" />
  <ContentTab title="Web" href="/cody/clients/cody-with-sourcegraph" />
  <ContentTab title="Cody Enterprise" href="/cody/clients/enable-cody-enterprise" />
</ContentTabs>
```

### Other MDX Files
- For other MDX files, use the ContentTabs component without the name prop.
- **Example: docs/cody//clients/install-vscode.mdx**
``` mdx
<ContentTabs>
  <ContentTab title="VS Code" href="/cody/clients/install-vscode" />
  <ContentTab title="JetBrains (beta)" href="/cody/clients/install-jetbrains" />
  <ContentTab title="Neovim (experimental)" href="/cody/clients/install-neovim" />
  <ContentTab title="Web" href="/cody/clients/cody-with-sourcegraph" />
  <ContentTab title="Cody Enterprise" href="/cody/clients/enable-cody-enterprise" />
</ContentTabs>
```

### CODE REVIEW

**Comment by zahidalidev** [comment]
@MaedahBatool please review this PR

**Comment by MaedahBatool** [comment]
@zahidalidev can you please remove the changes you made to the mdx files? Just leave the component files. I will make the changes to the MDX content myself.

**Comment by zahidalidev** [comment]
Sure, I have removed the changes for the .mdx and navigation files.

**Comment by MaedahBatool** [comment]
Awesome merging it now.

**Review by MaedahBatool — APPROVED** [review]

**Pull request merged**
