### PR TITLE
Embeddings configuration docs cleanup

### PR DESCRIPTION
**Pull request by loujar**
Removed references to deprecated embeddings service and associated configuration

### CODE REVIEW

**Review by MaedahBatool — APPROVED** [review]
TY :)

**Comment by loujar** [comment]
Some additional references to embeddings in our docsthat I left in place, but should be reviewed:
- https://sourcegraph.com/docs/admin/pings
  - a null `embeddings` field is still included in sg ping json
- https://sourcegraph.com/docs/cody/embedded-repos
  - I believe this page is no longer relevant and can be deleted
- https://sourcegraph.com/docs/cody/usage-and-pricing
  - not sure if community edition embeddings limits are still applicable
- https://sourcegraph.com/docs/admin/observability/alerts
  - embedding prometheus alerts are still listed here, but I believe this page is procedurally generated

**Review by jtibshirani — APPROVED** [review]
Thanks @loujar !

**Comment by anorrish** [comment]
@loujar Just to confirm, did you add the Embeddings link to the Core Concepts page just for PLG users (and so Ent users would see it's not available to them)?

**Comment by loujar** [comment]
@anorrish I added the links to the tokens & embeddings core concepts page since there was currently no direct navigation to them in our docs (that I could find). The embeddings doc already clearly articulates that embeddings no longer applies for enterprise users.

**Pull request merged**
